"use strict";
let decimal = 6;
let hex = 0xf00d;
let binary = 0b1010;
let octal = 0o744;
let notANumber = NaN;
let underscoreNum = 1000000;
console.log(decimal);
console.log(hex);
console.log(binary);
console.log(octal);
console.log(notANumber);
console.log(underscoreNum);
